export const mockLocData = {
  ip_address: '27.4.59.31',
  city: 'Bengaluru',
  city_geoname_id: 1277333,
  region: 'Karnataka',
  region_iso_code: 'KA',
  region_geoname_id: 1267701,
  postal_code: '560002',
  country: 'India',
  country_code: 'IN',
  country_geoname_id: 1269750,
  country_is_eu: false,
  continent: 'Asia',
  continent_code: 'AS',
  continent_geoname_id: 6255147,
  longitude: 77.5855,
  latitude: 12.9634,
  security: {
    is_vpn: false,
  },
  timezone: {
    name: 'Asia/Kolkata',
    abbreviation: 'IST',
    gmt_offset: 5,
    current_time: '10:55:28',
    is_dst: false,
  },
  flag: {
    emoji: '🇮🇳',
    unicode: 'U+1F1EE U+1F1F3',
    png: 'https://static.abstractapi.com/country-flags/IN_flag.png',
    svg: 'https://static.abstractapi.com/country-flags/IN_flag.svg',
  },
  currency: {
    currency_name: 'Indian Rupee',
    currency_code: 'INR',
  },
  connection: {
    autonomous_system_number: 17488,
    autonomous_system_organization: 'Hathway IP Over Cable Internet',
    connection_type: 'Cable/DSL',
    isp_name: 'Hathway IP over Cable Internet Access',
    organization_name: 'Hathway Cable and Datacom Limited',
  },
}
